apiVersion: v1
kind: Service

metadata:
  name: {{ include "fiber-http.fullname" . }}
  labels:
    {{- include "fiber-http.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    {{- include "fiber-http.selectorLabels" . | nindent 4 }}
  ports:
  # Send ingress traffic from the service to Envoy listening on port 9980.
  # Envoy will reverse proxy back to localhost:8480 for the real service
  # to handle the request. Must match `OPSANI_ENVOY_PROXY_SERVICE_PORT` above 
  # and be exposed as a `containerPort`.
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9980
