apiVersion: v1
kind: Secret
metadata:
  name: servo-token
  namespace: {{ .Values.opsani.namespace }}
  labels:
    app.kubernetes.io/name: servo
    app.kubernetes.io/component: core
type: Opaque
data:
  token: {{ .Values.opsani.token }}
